### ISSUE TITLE
Hall Effect Encoder implementation

### ISSUE THREAD

**Issue by jkleiber** [Sooner-Competitive-Robotics/RobotLib#5]
The Encoder class in RobotLib will not work with the hall effect sensor setup because it is built for quadrature encoders with two output pins. Therefore we need to either 1. Make a HallEffectEncoder class, or 2. Make the Encoder class handle single pin inputs like the hall effect case.

If #2 is implemented, use an enum to set the mode.

**Comment by noahzemlin** [comment]
Worked on here c0f941e4abecd08f78e98b17de8bdf9260fa37ba
Unknown if working.

**Comment by noahzemlin** [comment]
Closing this as it is technically implemented but will be improved with #10
