### ISSUE TITLE
Automatically extract keywords

### ISSUE THREAD

**Issue by noahzemlin** [Sooner-Competitive-Robotics/RobotLib#9]
Arduino projects contains a keywords.txt file that describes all keywords that should be highlighted in the Arduino IDE. It wants every class followed by KEYWORD1 and every method followed by KEYWORD2. This is very tedious and error prone to do by hand, so there should be a script that handles this automatically. This should also be put into the build process. This is related to #8.

https://www.arduino.cc/en/Hacking/LibraryTutorial

**Comment by ThaddeusMorris** [comment]
This project looks like it might be helpful.

https://github.com/r89m/arduino-keywords
